database:
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.hbm2ddl.auto: create  
        
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: leo

  # the password
  password: leoleo

  # the JDBC URL
  url: jdbc:mysql://localhost/DropwizardOauth2
  
logging:
  level: INFO

allowedGrantTypes:
  - password

bearerRealm: oauth2-provider
server:
  applicationConnectors:
    - type: http
      port: 9090